- hosts: all
  become: yes
  tasks:

    - name: Disable Transparent Huge Pages at boot
      lineinfile:
        path: /etc/rc.local
        line: "if [ -d /sys/kernel/mm/transparent_hugepage ]; then echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled ; echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag ; fi"
      register: transparent_hugepage
    - name: Disable disabled rc.local
      lineinfile:
        path: /etc/rc.local
        line: 'exit 0'
        state: absent
    - name: Disable Transparent Huge Pages at run time 1/2
      command: echo never > /sys/kernel/mm/transparent_hugepage/defrag
      when: transparent_hugepage|changed
    - name: Disable Transparent Huge Pages at run time 2/2
      command: echo never > /sys/kernel/mm/transparent_hugepage/enabled
      when: transparent_hugepage|changed
